apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    app: {{ include "redis.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      name: redis
  selector:
    app: {{ include "redis.name" . }}