replicaCount: 2

image:
  repository: myregistry/auth-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

env:
  eureka:
    defaultZone: "http://eureka-server:8761/eureka/"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
