apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-scripts
data:
  01-create-dbs.js: |
    db = db.getSiblingDB('events');
    db.createCollection('public_events');
    db = db.getSiblingDB('contents');
    db.createCollection('media');