apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: myregistry/my-user-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
          # Настройка подключения к PostgreSQL для User Service
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres:5432/userdb"
          - name: SPRING_DATASOURCE_USERNAME
            value: "user"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "password"
          # Настройка Eureka Client
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: "http://eureka-server:8761/eureka/"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: user-service
