server:
  port: 8083

spring:
  application:
    name: public-event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/eventdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

