FROM jenkins/inbound-agent:latest

USER root
RUN apt-get update && apt-get install -y docker.io maven curl && \
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash && \
    rm -rf /var/lib/apt/lists/*
  
USER jenkins
