server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    kubernetes:
      discovery:
        enabled: true       # включаем сервис-дискавери из Kubernetes
        all-namespaces: false
    gateway:                # определяем маршруты
      routes:

        # Входящие /api/v1/auth/**
      - id: auth-service
        uri: lb://auth-service             # lb:// — будет резолвиться через Kubernetes Discovery
        predicates:
        - Path=/api/v1/auth/**

        # Профиль
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/api/v1/users/**

        # Бронирования
      - id: booking-service
        uri: lb://booking-service
        predicates:
        - Path=/api/v1/bookings/**

        # События (публичные)
      - id: event-preview
        uri: lb://public-event-service
        predicates:
        - Path=/api/v1/events/preview
      - id: event-details
        uri: lb://public-event-service
        predicates:
        - Path=/api/v1/events/{id}

        # Админ-события
      - id: admin-event
        uri: lb://admin-event-service
        predicates:
        - Path=/api/v1/admin/events/**

        # Залы
      - id: hall-service
        uri: lb://hall-service
        predicates:
        - Path=/api/v1/events/{eventId}/hall

        # Покупки билетов
      - id: ticketing
        uri: lb://ticketing-service
        predicates:
        - Path=/api/v1/tickets/**

        # Доходы
      - id: income-service
        uri: lb://income-service
        predicates:
        - Path=/api/v1/admin/incomes/**

        # Отчёты
      - id: analytics
        uri: lb://analytics-service
        predicates:
        - Path=/api/v1/admin/reports/**

# Kubernetes discovery не требует других настроек по eureka

jwt:
  secret: mySecretKey