server:
  port: 8762

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: admin-event-service
          uri: lb://ADMIN-EVENT-SERVICE
          predicates:
            - Path=/api/v1/admin/**
        - id: public-event-service
          uri: lb://PUBLIC-EVENT-SERVICE
          predicates:
            - Path=/api/v1/events/**
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/booking/**
        - id: ticketing-service
          uri: lb://TICKETING-SERVICE
          predicates:
            - Path=/api/v1/tickets/**
        # Другие маршруты
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: mySecretKey