server:
  port: 8085

spring:
  application:
    name: admin-event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/eventdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
