apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-service
  labels:
    app: {{ include "postgresql.name" . }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      name: postgres
  selector:
    app: {{ include "postgresql.name" . }}