replicaCount: 3

image:
  repository: postgres
  tag: "14"
  pullPolicy: IfNotPresent

service:
  port: 5432

persistence:
  storageClass: "standard"
  size: 10Gi

postgresUser: user
postgresPassword: secret
