server:
  port: 8084

spring:
  application:
    name: content-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/contentdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
