replicaCount: 2

image:
  repository: localhost:5000//booking-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8087

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  eureka:
    defaultZone: "http://eureka-server:8761/eureka/"
