server:
  port: 8086

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://analytics-db:5432/analyticsdb
    username: analytics
    password: analyticspassword
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: analytics-group
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
