replicaCount: 1

image:
  repository: localhost:5000//analytics-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8086

env:
  eureka:
    defaultZone: "http://eureka-server:8761/eureka/"
  kafka:
    bootstrapServers: "kafka:9092"

resources:
  limits:
    cpu: "300m"
    memory: "256Mi"
  requests:
    cpu: "150m"
    memory: "128Mi"
