global:
  imagePullPolicy: IfNotPresent
  eureka:
    defaultZone: "http://eureka-server:8761/eureka/"
  environment: production

gateway-service:
  replicaCount: 2
  image:
    repository: localhost:5000//gateway-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 8080

auth-service:
  replicaCount: 2
  image:
    repository: localhost:5000//auth-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 8081

user-service:
  replicaCount: 2
  image:
    repository: localhost:5000//user-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 8082

public-event-service:
  replicaCount: 2
  image:
    repository: localhost:5000//public-event-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 8083

admin-event-service:
  replicaCount: 2
  image:
    repository: localhost:5000//admin-event-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 8085

booking-service:
  replicaCount: 2
  image:
    repository: localhost:5000//booking-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 8087

ticketing-service:
  replicaCount: 2
  image:
    repository: localhost:5000//ticketing-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 8088

payment-service:
  replicaCount: 1
  image:
    repository: localhost:5000//payment-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 8089

notification-service:
  replicaCount: 2
  image:
    repository: localhost:5000//notification-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 8090

analytics-service:
  replicaCount: 1
  image:
    repository: localhost:5000//analytics-service
    tag: "latest"
  service:
    type: ClusterIP
    port: 8086
