replicaCount: 3

image:
  repository: mongo
  tag: "5.0"
  pullPolicy: IfNotPresent

service:
  port: 27017

persistence:
  storageClass: "standard"
  size: 20Gi

extraVolumes:
  - name: mongo-init-scripts
    configMap:
      name: mongodb-init-scripts

extraVolumeMounts:
  - name: mongo-init-scripts
    mountPath: /docker-entrypoint-initdb.d