image:
  repository: mongo
  tag: "4.4.6"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  storageClass: "hostpath"      # пустая строка = default StorageClass кластера
  accessModes:
    - ReadWriteOnce
  size: 10Gi

initScripts:
  enabled: true         # при true создаёт ConfigMap + Job для инициализации
